use * from types


// CloudEvent
// record cloudevent {
//     "id": string,
//     "source": string,
//     "specversion": string,
//     "type": string,
// }

// record cloudevent-options {
//     "datacontenttype": option<string>,
//     "dataschema": option<string>,
//     "subject": option<string>,
//     "time": option<string>,
//     "data": option<data>,
// }

// type cloudevent = string

ce-handler: function(event: string) -> expected<string, error>