name: Rust
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install wasi-sdk"
        run: |
          set -x
          curl -sS -L -O https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-linux.tar.gz
          tar xf wasi-sdk-12.0-linux.tar.gz
          sudo mkdir -p /opt/wasi-sdk
          sudo mv wasi-sdk-12.0/* /opt/wasi-sdk/
      - name: "Install Wasm Rust targets"
        run: |
          rustup target add wasm32-wasi
          rustup target add wasm32-unknown-unknown

      - name: "Install Redis"
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.2'
          auto-start: "false"
      
      - name: "Install TiUP"
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
          source /home/runner/.profile
          which tiup
          tiup playground --mode tikv-slim

      - name: Build
        run: cargo build
      - name: Run simple test
        run:
          cargo test --all --all-features -- --nocapture
